### ISSUE TITLE
Error on adding symproxy

### ISSUE THREAD

**Issue by dhirastu** [shchahrykovich/AwesomePdb#1]
Step 8/14 : ADD Tools\\symproxy.dll C:\\Windows\\System32\\inetsrv\\symproxy.dll
ADD failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder484890675\Tools\symproxy.dll: The system cannot find the path specified.

Any suggestion?

BTW, Thanks for the project

**Comment by shchahrykovich** [comment]
I've updated [readme](https://github.com/shchahrykovich/AwesomePdb/blob/master/SymProxy/Tools/readme.md)

You can find these files in the installation folder of WinDbg.

**Comment by adwaitasolutions** [comment]
That gave me some clue. Thanks!!!
